version: '3.8'
services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    image: node:18-alpine
    ports:
      - "3131:3131"
    volumes:
      - ./backend:/app
      - ./photos:/app/photos
    working_dir: /app
    # Capture output of npm install and node server.js to docker logs
    command: /bin/sh -c "npm install && node server.js > startup.log 2>&1 && cat startup.log"
    environment:
      - NODE_ENV=development
